version: '3'
services:
  db_1:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news

  postgres_db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: result
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  db:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: moex
  app:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
    restart: on-failure
    volumes:
      - /home/avu/IdeaProjects/sdb/output:/home/result
    depends_on:
      - db
      - db_1
      - postgres_db