version: '3'
services:
  db_1:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'test'
  postgres_db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
  db:
    image: mongo:4.0.4
    ports:
      - "4536:4536"
  app:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
    depends_on:
      - db
      - db_1
      - postgres_db